Create Eavesdropping.py
tqsd/QuNetSim pull request #104
Opened 2021-05-16 12:24 UTC by pritamsinha2304

Issue #79
Replaced the outdated sniffing function

2021-05-16 15:55 UTC, stephendiadamo requested changes

2021-05-16 15:55 UTC, stephendiadamo commented on examples/Eavesdropping on channels/Eavesdropping.py
> +amount_transmit = 5
Constants should be all upper case.

2021-05-16 15:55 UTC, stephendiadamo commented on examples/Eavesdropping on channels/Eavesdropping.py
> +    host_eve.delay = 0.2
Delay probably unneeded.

2021-05-16 15:56 UTC, stephendiadamo commented on examples/Eavesdropping on channels/Eavesdropping.py
> +    host_eve.delay = 0.2
Just small changes. Also could you change the file path to be camel case?

2021-05-16 15:56 UTC, stephendiadamo commented
Just small changes. Also could you change the file path to be camel case?

2021-05-16 16:15 UTC, pritamsinha2304 commented
I am sorry, if I mess up something while commit, merge etc., because this is my first open source contribution and also with Github

2021-05-16 16:20 UTC, pritamsinha2304 commented
> Just small changes. Also could you change the file path to be pothole case?

Can you tell what do you mean by "pothole case" ? I don't get it

2021-05-16 16:23 UTC, stephendiadamo commented
> pothole case

It just means `something_like_this`. All lowercase, spaces are `_`.

2021-05-16 16:27 UTC, stephendiadamo commented
No problem, you did everything fine. Just small inconsistencies with the
project style that I'd like you to change before I merge.

Thanks,
Stephen

On Sun, 16 May 2021, 18:15 pritamsinha2304, ***@***.***>
wrote:

> I am sorry, if I mess up something while commit, merge etc., because this
> is my first open source contribution and also with Github
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tqsd/QuNetSim/pull/104#issuecomment-841838852>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJDSBIPJIS337E7LKBIP3DTN7VRRANCNFSM446ZW6HQ>
> .
>

2021-05-16 16:57 UTC, pritamsinha2304 commented
> > pothole case
> 
> It just means `something_like_this`. All lowercase, spaces are `_`.

I changed it. I think I did it correctly

2021-05-17 14:27 UTC, stephendiadamo requested changes
Sorry, very minor thing but can you change the filename to be all lowercase?

2021-05-17 14:39 UTC, pritamsinha2304 commented
> Sorry, very minor thing but can you change the filename to be all lowercase?

No problem

2021-05-17 17:32 UTC, stephendiadamo approved these changes

2021-05-17 17:32 UTC, merged