Deprecated `add_data_qubit` to `add_qubit` [unitaryhack]
tqsd/QuNetSim pull request #138
Opened 2022-06-17 08:34 UTC by divshacker

fixes #136

2022-06-20 13:50 UTC, stephendiadamo requested changes
I see the deprecation message, but I don't see the new `add_qubit` method added to the Host component. It needs to be added.

2022-06-20 13:50 UTC, stephendiadamo commented on qunetsim/components/host.py
> +        warnings.warn(
I see the deprecation message, but. I don't see the new method called `add_qubit`. It seems to be missing... Do the tests pass with this code?

2022-06-20 17:11 UTC, divshacker commented
I have added the function, Please check now and let me know further changes

2023-04-14 10:58 UTC, SimonSekavcnik approved these changes
Approved.

2023-04-14 11:15 UTC, divshacker commented
Took ten months to test and approve ? 🙂

2023-04-14 12:32 UTC, SimonSekavcnik commented
Sorry about that.

2023-04-20 09:38 UTC, stephendiadamo approved these changes

2023-04-20 09:38 UTC, merged